ALTER TABLE public.monthly_ot_adjustments
  ADD COLUMN IF NOT EXISTS include_ot BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS include_epf BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS include_etf BOOLEAN NOT NULL DEFAULT true;