
ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS contact_no TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_code TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_branch TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS branch_code TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '';
